
defaults:
  - hydra: default
  - model: deflow
  
slurm_id: 00000000
exp_note: None
exp_id: ${model.exp_id}_ep_${epochs}_lr_${lr}_bs_${batch_size}_${exp_note}

wandb_mode: disabled # [offline, disabled, online]
wandb_project_name: sceneflow_translation_voting
wandb_run_name: ${exp_id}

use_demo_data: False
train_data: data/Argoverse2/preprocess_v2/sensor/train
val_data: data/Argoverse2/preprocess_v2/sensor/train

output: ${model.name}-${slurm_id}

checkpoint: 
pretrained_weights: 
eval_only: False

# trainer
num_workers: 8
gpus: 1 # will change in code: torch.cuda.device_count()
sync_bn: true
batch_size: 1
epochs: 3
gradient_clip_val: 5.0

# optimizer ==> Adam
lr: 2e-6
loss_fn: warpedLoss # choices: [ff3dLoss, zeroflowLoss, deflowLoss, seflowLoss]
add_seloss: # {chamfer_dis: 1.0, static_flow_loss: 1.0, dynamic_chamfer_dis: 1.0, cluster_based_pc0pc1: 1.0}

# log settings
seed: 42069
log_every: 10 # steps epochs*dataset_size/batch_size
val_every: 4 # epochs
save_top_model: 5 # top_k model will be saved.

# -----> Model and Task Parameters
voxel_size: [0.2, 0.2, 0.2]
point_cloud_range: [-51.2, -51.2, -3, 51.2, 51.2, 3]
num_frames: 2