name: sf_voxel_model

target:
  _target_: src.models.SFVoxelModel
  nframes: 1
  m: 8
  n: 64
  input_channels: 32
  output_channels: 64
  point_cloud_range: ${point_cloud_range}
  voxel_size: ${voxel_size}
  grid_feature_size: [512, 512]
  decoder: 'decoder'
  use_bn_in_vol: False
  use_ball_query: False
  vol_conv_hidden_dim: 16

val_monitor: val/Dynamic/Mean
exp_id: ${model.name}_m_${model.target.m}_n_${model.target.n}